### PR TITLE
Refactored version

### PR DESCRIPTION
**Pull request by monester**
Hi!
I rewrite your library from scratch and now all objects are defined in json.
Also function now return promises, not the answer and if someone tests for type of answer (dict or list) it would break code.

However all public interfaces are left the same, so it won't break anything.

The only thing left to do is documentation, because existing autodoc wasn't able to find objects generated by metaclass.

### CODE REVIEW

**Comment by svartalf** [comment]
It looks amazing, yet I need time to review all the changes :)

**Comment by monester** [comment]
If you have any questions - ask, I can explain why I've made it such way.

**Comment by svartalf** [comment]
@monester is there any chance to contact you personally?

**Comment by monester** [comment]
You can contact me via acharykov@mirantis.com

**Pull request merged**
