### PR TITLE
add parameter to select wargaming cluster for API requests

### PR DESCRIPTION
**Pull request by Geno1**
Hi,

just made a little patch to make your package usable with the other wargaming clusters.

### CODE REVIEW

**Comment by svartalf** [comment]
Probably, something like this will be better and more flexible:

```
api = wargaming.WoT('app_id', base_url='https://api.worldoftanks.eu/wot/')
```

Also, support for that functionality almost done. What do you think about that?

**Comment by Geno1** [comment]
Well, it's certainly more flexible, but means users will have to manage the URLs themselves. Not a big deal, and personally I don't really care one way or the other.
Thinking about it I guess that approach would allow you to merge the different games into a single API handler with functionality defined by the passed URL.

**Comment by svartalf** [comment]
@Geno1, yeah, probably you're right. I had found that beautiful fork yesterday, probably something similar should be done: https://github.com/monester/python-wargaming

**Comment by monester** [comment]
This functionality was added, please checks docs for region support. http://python-wargaming.readthedocs.io/en/latest/

**Pull request closed without merging**
